FROM --platform=linux/amd64 ubuntu:22.04
ENV SQLALCHEMY_DATABASE_URI=sqlite:///:memory:

# Installing dependencies for running a python application
RUN apt-get update && apt-get install -y python3 python3-pip postgresql-client libpq-dev libcurl4-openssl-dev libssl-dev  wget && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
# Install pipenv
RUN pip3 install poetry celery[redis] watchtower
# Setting the working directory
WORKDIR /app
# Install pipenv dependencies
COPY pyproject.toml ./
RUN poetry install --no-root
# Copying our application into the container
COPY bin bin
COPY spamoverflow spamoverflow
# Get the version of spamhammer that matches the architecture of the container
RUN dpkg --print-architecture | grep -q "amd64" && export SPAMHAMMER_ARCH="amd64" || export SPAMHAMMER_ARCH="arm64" && wget https://github.com/CSSE6400/SpamHammer/releases/download/v1.0.0/spamhammer-v1.0.0-linux-${SPAMHAMMER_ARCH} -O spamoverflow/spamhammer && chmod +x spamoverflow/spamhammer
# Running our application
CMD ["poetry", "run", "flask", "--app", "spamoverflow", "run", "--host", "0.0.0.0", "--port", "8080"]
